import 'package:flutter/material.dart';

class ColorThemes {
  static ColorScheme get light => const ColorScheme(
        brightness: Brightness.light,
        primary: Color(0xFF00677D),
        onPrimary: Color(0xFFFFFFFF),
        primaryContainer: Color(0xFFB2EBFF),
        onPrimaryContainer: Color(0xFF001F27),
        secondary: Color(0xFF4B626A),
        onSecondary: Color(0xFFFFFFFF),
        secondaryContainer: Color(0xFFCEE7F0),
        onSecondaryContainer: Color(0xFF061E25),
        tertiary: Color(0xFF006876),
        onTertiary: Color(0xFFFFFFFF),
        tertiaryContainer: Color(0xFF9EEFFF),
        onTertiaryContainer: Color(0xFF001F24),
        error: Color(0xFFBA1A1A),
        errorContainer: Color(0xFFFFDAD6),
        onError: Color(0xFFFFFFFF),
        onErrorContainer: Color(0xFF410002),
        background: Color(0xFFFDFCFF),
        onBackground: Color(0xFF1A1C1E),
        surface: Color(0xFFFDFCFF),
        onSurface: Color(0xFF1A1C1E),
        surfaceVariant: Color(0xFFDBE4E8),
        onSurfaceVariant: Color(0xFF40484B),
        outline: Color(0xFF70787C),
        onInverseSurface: Color(0xFFF1F0F4),
        inverseSurface: Color(0xFF2F3033),
        inversePrimary: Color(0xFF31D7FF),
        shadow: Color(0xFF000000),
        surfaceTint: Color(0xFF00677D),
        // outlineVariant: Color(0xFFBFC8CC),
        // scrim: Color(0xFF000000),
      );

  static ColorScheme get dark => const ColorScheme(
        brightness: Brightness.dark,
        primary: Color(0xFF31D7FF),
        onPrimary: Color(0xFF003642),
        primaryContainer: Color(0xFF004E5E),
        onPrimaryContainer: Color(0xFFB2EBFF),
        secondary: Color(0xFFB3CAD3),
        onSecondary: Color(0xFF1D343B),
        secondaryContainer: Color(0xFF344A52),
        onSecondaryContainer: Color(0xFFCEE7F0),
        tertiary: Color(0xFF50D7EE),
        onTertiary: Color(0xFF00363E),
        tertiaryContainer: Color(0xFF004E59),
        onTertiaryContainer: Color(0xFF9EEFFF),
        error: Color(0xFFFFB4AB),
        errorContainer: Color(0xFF93000A),
        onError: Color(0xFF690005),
        onErrorContainer: Color(0xFFFFDAD6),
        background: Color(0xFF1A1C1E),
        onBackground: Color(0xFFE3E2E6),
        surface: Color(0xFF1A1C1E),
        onSurface: Color(0xFFC6C6CA),
        surfaceVariant: Color(0xFF40484B),
        onSurfaceVariant: Color(0xFFBFC8CC),
        outline: Color(0xFF899296),
        onInverseSurface: Color(0xFF1A1C1E),
        inverseSurface: Color(0xFFE3E2E6),
        inversePrimary: Color(0xFF00677D),
        shadow: Color(0xFF000000),
        surfaceTint: Color(0xFF31D7FF),
        // outlineVariant: Color(0xFF40484B),
        // scrim: Color(0xFF000000),
      );
}
