name: widget
publish_to: none

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  source:
    path: ../../package/source
  common:
    path: ../../package/common
  theme:
    path: ../../package/theme

dev_dependencies:
  flutter_lints: ^2.0.0